### ISSUE TITLE
Error with invoke command in Python 3.8

### ISSUE THREAD

**Issue by avleze** [raiben/made_recommender#34]
I have created a Virtual Enviroment with Python 3.8.1 and have installed the dependencies with:

`pip install -r requirements.txt`

Then I have run the command `invoke --list` and I get the error that you could see below.

```(venv) [x-pc made_recommender]$ invoke --list
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
Traceback (most recent call last):
  File "unrevealed-path/made_recommender/venv/bin/invoke", line 10, in <module>
    sys.exit(program.run())
  File "unrevealed-path/made_recommender/venv/lib/python3.8/site-packages/invoke/program.py", line 321, in run
    self.parse_collection()
  File "unrevealed-path/made_recommender/venv/lib/python3.8/site-packages/invoke/program.py", line 399, in parse_collection
    self.load_collection()
  File "unrevealed-path/made_recommender/venv/lib/python3.8/site-packages/invoke/program.py", line 588, in load_collection
    module, parent = loader.load(coll_name)
  File "unrevealed-path/made_recommender/venv/lib/python3.8/site-packages/invoke/loader.py", line 75, in load
    module = imp.load_module(name, fd, path, desc)
  File "/usr/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "unrevealed-path/made_recommender/tasks.py", line 8, in <module>
    from rating_evaluator.evaluator_builder import EvaluatorBuilder
  File "unrevealed-path/made_recommender/rating_evaluator/evaluator_builder.py", line 11, in <module>
    from sklearn.neural_network import MLPRegressor
  File "unrevealed-path/made_recommender/venv/lib/python3.8/site-packages/sklearn/__init__.py", line 64, in <module>
    from .base import clone
  File "unrevealed-path/made_recommender/venv/lib/python3.8/site-packages/sklearn/base.py", line 12, in <module>
    from scipy import sparse
  File "unrevealed-path/made_recommender/venv/lib/python3.8/site-packages/scipy/sparse/__init__.py", line 230, in <module>
    from .csr import *
  File "unrevealed-path/made_recommender/venv/lib/python3.8/site-packages/scipy/sparse/csr.py", line 13, in <module>
    from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks,
ImportError: numpy.core.multiarray failed to import
```

**Comment by avleze** [comment]
I just have tested it with Python 3.7.6 and it works.

**Comment by JJ** [comment]
So it's a problem with Python 3.8. Thanks! We'll have to update it.

**Comment by avleze** [comment]
No problem! It was only for you to know...
